spring.application.name=nurser
spring.r2dbc.name=nurser
spring.r2dbc.password=admin
spring.r2dbc.url=r2dbc:postgresql://localhost:5432
spring.r2dbc.username=admin
jwt.security.key=aiAL184O6avpS0KwBRmSVQTCzvwqjtI/UpP6dLW3aA0evp6pkok/78KqoVF3oAdh1X/fqLAznw+yeWtokHHB7g==


# Flyway
spring.flyway.url=jdbc:postgresql://localhost:5432/nurser
spring.flyway.user=admin
spring.flyway.password=admin
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
